version: '3.8'

services:
  mysql-docker-demo:
    image: mysql:8.0.32
    restart: unless-stopped
    networks:
      - docker-demo-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_PASSWORD=rootPassword
      - MYSQL_DATABASE=docker_demo_db
    ports:
      - '3308:3306'

  docker-demo:
    image: docker-demo-31052023
    ports:
      - '9081:9081'
    networks:
      - docker-demo-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-demo:3306/docker_demo_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'rootPassword'
    build: ./
    restart: unless-stopped
    depends_on:
      - mysql-docker-demo

networks:
  docker-demo-network:
    name: docker-demo-network
    driver: bridge


# docker-compose config
# docker-compose up
# check database
# docker exec -it 002 bin/bash  -> bash-4.4# mysql -uroot -p docker_demo_db -> Enter password: *********
# mysql> show databases; -> use docker_demo_db; -> show tables; -> select * from logins; -> Empty set (0.00 sec)
# -> insert into logins value (1, 'subhi', 'subhi_80'); -> Query OK, 1 row affected (0.01 sec) -> select * from logins;
# +----+-------+----------+
# | id | name  | username |
# +----+-------+----------+
# |  1 | subhi | subhi_80 |
# +----+-------+----------+
# exit; -> Bye #bash-4.4# -> exit;
