server:
  port: 9081

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/docker_demo_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    #url: jdbc:mysql://mysql-docker-demo-container:3306/docker_demo_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: rootPassword
  # none: The default for MySQL. No change is made to the database structure.
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
